import os
from uuid import uuid4
import asyncpg
import pytest
from backend.store import Store


@pytest.mark.asyncio
async def test_postgres_transactions_deduplication_and_restart():
    url = os.environ.get('TEST_DATABASE_URL')
    if not url:
        pytest.skip('Set TEST_DATABASE_URL to a dedicated disposable Postgres database')
    store=Store(url); await store.open()
    chat=await store.create_chat(); rid=uuid4(); pending=uuid4()
    try:
        await store.accept(chat['id'],rid,'hello')
        with pytest.raises(asyncpg.UniqueViolationError):
            await store.accept(chat['id'],rid,'duplicate')
        assert len(await store.messages(chat['id']))==1
        await store.complete(chat['id'],rid,'answer')
        assert [m['content'] for m in await store.messages(chat['id'])]==['hello','answer']
        await store.accept(chat['id'],pending,'interrupted question')
    finally: await store.close()
    store=Store(url); await store.open()
    try:
        rows=await store.messages(chat['id'])
        assert rows[-1]['run_status']=='interrupted'
        assert [m['content'] for m in await store.context(chat['id'],uuid4())]==['hello','answer']
    finally:
        # Only remove the rows generated by this test in the explicit test database.
        async with store.pool.acquire() as db, db.transaction():
            await db.execute('DELETE FROM messages WHERE conversation_id=$1',chat['id'])
            await db.execute('DELETE FROM runs WHERE conversation_id=$1',chat['id'])
            await db.execute('DELETE FROM conversations WHERE id=$1',chat['id'])
        await store.close()
