import os
from uuid import uuid4
import asyncpg
import pytest
from backend.store import Store


@pytest.mark.asyncio
async def test_postgres_transactions_deduplication_and_restart():
    url = os.environ.get('TEST_DATABASE_URL')
    if not url:
        pytest.skip('Set TEST_DATABASE_URL to a dedicated disposable Postgres database')
    store=Store(url); await store.open()
    chat=await store.create_chat(); rid=uuid4(); pending=uuid4()
    try:
        await store.accept(chat['id'],rid,'hello')
        with pytest.raises(asyncpg.UniqueViolationError):
            await store.accept(chat['id'],rid,'duplicate')
        assert len(await store.messages(chat['id']))==1
        await store.complete(chat['id'],rid,'answer')
        assert [m['content'] for m in await store.messages(chat['id'])]==['hello','answer']
        await store.accept(chat['id'],pending,'interrupted question')
        await store.reserve_sandbox(rid)
        await store.sandbox_created(rid,'test-sandbox')
        await store.sandbox_stopped(rid,5)
        await store.reserve_sandbox(pending)
        await store.tool_step(rid,1,'python',{'code':'print(42)'},'done','42')
        await store.tool_step(pending,1,'terminal',{'command':'sleep 20'},'running')
        artifact=await store.save_artifact(chat['id'],rid,'test.csv','application/octet-stream',b'n\n42\n')
    finally: await store.close()
    store=Store(url); await store.open()
    try:
        rows=await store.messages(chat['id'])
        assert rows[-1]['run_status']=='interrupted'
        assert [m['content'] for m in await store.context(chat['id'],uuid4())]==['hello','answer']
        assert (await store.sandbox_budget())['total_seconds'] >= 185
        assert (await store.tools(chat['id']))[-1]['status']=='interrupted'
        assert (await store.file(artifact['id']))['data']==b'n\n42\n'
        # Reservations are atomic and survive a restart; reaching the rolling cap fails closed.
        await store.pool.execute("UPDATE sandbox_usage SET reserved_seconds=180 WHERE run_id=$1",rid)
        extra=[]
        for i in range(18):
            new=uuid4();extra.append(new);await store.accept(chat['id'],new,'budget test')
            await store.reserve_sandbox(new)
        blocked=uuid4();await store.accept(chat['id'],blocked,'blocked')
        with pytest.raises(ValueError,match='allowance'):
            await store.reserve_sandbox(blocked)
    finally:
        # Only remove the rows generated by this test in the explicit test database.
        async with store.pool.acquire() as db, db.transaction():
            await db.execute('DELETE FROM tool_steps WHERE run_id IN (SELECT id FROM runs WHERE conversation_id=$1)',chat['id'])
            await db.execute('DELETE FROM sandbox_usage WHERE run_id IN (SELECT id FROM runs WHERE conversation_id=$1)',chat['id'])
            await db.execute('DELETE FROM artifacts WHERE conversation_id=$1',chat['id'])
            await db.execute('DELETE FROM messages WHERE conversation_id=$1',chat['id'])
            await db.execute('DELETE FROM runs WHERE conversation_id=$1',chat['id'])
            await db.execute('DELETE FROM conversations WHERE id=$1',chat['id'])
        await store.close()
