# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\nstreamchat\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\\\n\x0fGenerateRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12%\n\x08messages\x18\x02 \x03(\x0b\x32\x13.streamchat.Message\x12\x12\n\nmax_tokens\x18\x03 \x01(\r\":\n\x05\x43hunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\x15\n\rfinish_reason\x18\x03 \x01(\t\"\x0e\n\x0cReadyRequest\"*\n\nReadyReply\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\r\n\x05model\x18\x02 \x01(\t2\x86\x01\n\x0bModelWorker\x12<\n\x08Generate\x12\x1b.streamchat.GenerateRequest\x1a\x11.streamchat.Chunk0\x01\x12\x39\n\x05Ready\x12\x18.streamchat.ReadyRequest\x1a\x16.streamchat.ReadyReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=27
  _globals['_MESSAGE']._serialized_end=67
  _globals['_GENERATEREQUEST']._serialized_start=69
  _globals['_GENERATEREQUEST']._serialized_end=161
  _globals['_CHUNK']._serialized_start=163
  _globals['_CHUNK']._serialized_end=221
  _globals['_READYREQUEST']._serialized_start=223
  _globals['_READYREQUEST']._serialized_end=237
  _globals['_READYREPLY']._serialized_start=239
  _globals['_READYREPLY']._serialized_end=281
  _globals['_MODELWORKER']._serialized_start=284
  _globals['_MODELWORKER']._serialized_end=418
# @@protoc_insertion_point(module_scope)
